# kwplayer.spec
# Used to build rpm for kwplayer on Fedora 19/20/21/22
# Released by mosquito <sensor.wen@gmail.com>, wangjiezhe <wangjiezhe@gmail.com>
# This spec file is published under the GPLv3 license

# Template is originally generated by "rpmdev-newspec -t python"
%{!?python3_sitelib: %global python3_sitelib %(%{__python3} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")}

Name:		kwplayer
Version:	3.4.8
Release:	1%{?dist}
Summary:	An elegant music player which can get songs from kuwo.cn

License:	GPLv3
URL:		https://github.com/LiuLang/kwplayer
Source:		%{name}-%{version}.tar.xz

# Followings are not needed by Fedora after 17 and will be ignored by rpmbuild
# Group:	Applications/Multimedia

BuildArch:	noarch
BuildRequires:	python3-devel

Requires:	python3-cairo
Requires:	python3-dbus
Requires:	python3-gobject
Requires:	python3-ply
Requires:	gstreamer1-plugins-base
Requires:	gstreamer1-plugins-good
Requires:	gstreamer1-plugins-ugly
Requires:	gstreamer1-libav
Requires:	gstreamer1
Requires:	gstreamer-python
Requires:	libnotify
Requires:	pulseaudio
Requires:	pulseaudio-module-x11
# Not installed by default in KDE
Requires:	gnome-icon-theme-symbolic
# Optional:
Requires:	leveldb
Requires:	python3-plyvel
Requires:	python3-mutagen
Requires:	python3-keybinder
Requires:	python3-html2text

%description
KW music player is used to get music resources from Internet.
It can also play MV, show lyrics and show photo albums of artists.

%prep
%setup -q

%build
%{__python3} setup.py build

%install
rm -rf $RPM_BUILD_ROOT
%{__python3} setup.py install -O1 --skip-build --root=%{buildroot}

%find_lang %{name}

%clean
rm -rf $RPM_BUILD_ROOT

%post
cd %{python3_sitelib}
for file in kwplayer*
do
    if [[ -f $file && $file != "kwplayer-%{version}-py%{python3_version}.egg-info" ]]
    then
	rm $file
    fi
done

%files -f %{name}.lang
%doc LICENSE README.md HISTORY
%{_bindir}/%{name}
%{_datadir}/icons/hicolor/*
%{_datadir}/kwplayer/icons/*
%{_datadir}/applications/%{name}.desktop
%{python3_sitelib}/kuwo/*
%{python3_sitelib}/%{name}-%{version}-py%{python3_version}.egg-info
# generated by python3
%exclude %{python3_sitelib}/kuwo/__pycache__
